/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tarbaniker.endevina;

import java.sql.SQLException;



/**
 *
 * @author enric
 */


    
public class frameEndevina extends javax.swing.JFrame {
      
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameEndevina.class.getName());
    
    /**
     * Creates new form frameEndevina
     */
    public frameEndevina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        animal = new javax.swing.JTextField();
        labelAnimal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Endevina animal");
        setBackground(new java.awt.Color(51, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 153, 51));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setName("pantalla1"); // NOI18N

        jLabel1.setLabelFor(animal);
        jLabel1.setText("Quin animal?");

        animal.setAction(animal.getAction());
        animal.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                animalInputMethodTextChanged(evt);
            }
        });
        animal.addActionListener(this::animalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animal, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
        // de moment res
        System.out.println("1) Animal entrat ->"+animal.getText()+"<-");
        labelAnimal.setText(animal.getText());
        try {
            endevinaAnimal();
        } catch (SQLException ex) {
            System.getLogger(frameEndevina.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        System.out.println("1) final");
    }//GEN-LAST:event_animalActionPerformed

    private void animalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_animalInputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("2) Animal entrat ->"+animal.getText()+"<-");
        System.out.println("2) Final");
    }//GEN-LAST:event_animalInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("static-access")
    public void main(String args[])  {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Obertura/Creació de la base de dades SQLITE */
        conn.creaBD();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameEndevina().setVisible(true));
    }
    
    private  void endevinaAnimal () throws SQLException {
        
        // llegir animal #1
        var resultat =conn.llegirAnimal(1);
        // de moment només faint printf per veure que em funciona el SELECT
        System.out.printf("nom ->%s<-\n",resultat.get(0));
        System.out.printf("pregunta ->%s<-\n",resultat.get(1));
        System.out.printf("id SI ->%s<-\n", resultat.get(2));
        System.out.printf("id NO ->%s<-\n", resultat.get(3));

        // compte quants animals hi ha
        var quants = conn.quantsAnimals();
        System.out.printf("Hi ha %d animals", quants);

        // inserir una fila
        conn.inserirAnimal(quants+1, "gat", "pot amagar les urpes", quants+2, quants+3);
        
        // actualitzar una fila
        conn.actualitzarAnimal(10, "*", 81, 82);
        
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField animal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAnimal;
    // End of variables declaration//GEN-END:variables

    private static final connectaBD conn = new connectaBD();
}
