/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tarbaniker.endevina;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JDialog;


/**
 *
 * @author enric
 */


    
public class frameEndevina extends javax.swing.JFrame {
      
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameEndevina.class.getName());
    
    /**
     * Creates new form frameEndevina
     */
    public frameEndevina() {
        initComponents();
        // aquest setLocation... se suposa que centrarà la finestra
        setLocationRelativeTo(null);
        PanellPrimer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_pensar = new javax.swing.JLabel();
        Buto_pensat = new javax.swing.JButton();
        PanellPrimer = new javax.swing.JPanel();
        labelPregunta = new javax.swing.JLabel();
        Buto_SI = new javax.swing.JButton();
        Buto_NO = new javax.swing.JButton();
        PanellSegon = new javax.swing.JPanel();
        label_animal = new javax.swing.JLabel();
        animal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pregunta = new javax.swing.JTextField();
        Buto_afegir = new javax.swing.JButton();
        Buto_sortir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Endevina animal");
        setBackground(new java.awt.Color(51, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 153, 51));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setName("pantalla1"); // NOI18N

        label_pensar.setLabelFor(animal);
        label_pensar.setText("Pensa un animal, prem butó");

        Buto_pensat.setAction(Buto_pensat.getAction());
        Buto_pensat.setText("Pensat");
        Buto_pensat.addActionListener(this::Buto_pensatActionPerformed);

        labelPregunta.setBackground(new java.awt.Color(255, 204, 255));
        labelPregunta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Buto_SI.setAction(Buto_SI.getAction());
        Buto_SI.setText("Sí");
        Buto_SI.addActionListener(this::Buto_SIActionPerformed);

        Buto_NO.setAction(Buto_NO.getAction());
        Buto_NO.setText("No");
        Buto_NO.addActionListener(this::Buto_NOActionPerformed);

        label_animal.setText("Animal nou");
        label_animal.setToolTipText("");

        animal.setAction(animal.getAction());
        animal.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                animalInputMethodTextChanged(evt);
            }
        });

        jLabel1.setText("Pregunta per distingir aquest nou animal");
        jLabel1.setToolTipText("");

        pregunta.setAction(animal.getAction());

        Buto_afegir.setAction(Buto_afegir.getAction());
        Buto_afegir.setText("Afegir animal i pregunta");
        Buto_afegir.setToolTipText("");
        Buto_afegir.addActionListener(this::Buto_afegirActionPerformed);

        javax.swing.GroupLayout PanellSegonLayout = new javax.swing.GroupLayout(PanellSegon);
        PanellSegon.setLayout(PanellSegonLayout);
        PanellSegonLayout.setHorizontalGroup(
            PanellSegonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellSegonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanellSegonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanellSegonLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(PanellSegonLayout.createSequentialGroup()
                        .addGroup(PanellSegonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addComponent(animal)
                            .addComponent(Buto_afegir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanellSegonLayout.setVerticalGroup(
            PanellSegonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellSegonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buto_afegir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Buto_sortir.setAction(Buto_sortir.getAction());
        Buto_sortir.setBackground(new java.awt.Color(255, 0, 0));
        Buto_sortir.setText("Sortir");
        Buto_sortir.addActionListener(this::Buto_sortirActionPerformed);

        javax.swing.GroupLayout PanellPrimerLayout = new javax.swing.GroupLayout(PanellPrimer);
        PanellPrimer.setLayout(PanellPrimerLayout);
        PanellPrimerLayout.setHorizontalGroup(
            PanellPrimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellPrimerLayout.createSequentialGroup()
                .addComponent(PanellSegon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(PanellPrimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanellPrimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanellPrimerLayout.createSequentialGroup()
                        .addComponent(labelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buto_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buto_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Buto_sortir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanellPrimerLayout.setVerticalGroup(
            PanellPrimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellPrimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanellPrimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Buto_SI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(Buto_NO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPregunta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanellSegon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buto_sortir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_pensar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Buto_pensat))
            .addComponent(PanellPrimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buto_pensat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pensar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanellPrimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_animalInputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("2) Animal entrat ->"+animal.getText()+"<-");
        System.out.println("2) Final");
    }//GEN-LAST:event_animalInputMethodTextChanged

    private void Buto_pensatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buto_pensatActionPerformed
        // TODO add your handling code here:
        System.out.println("Butó 'Pensat' ");
        iniciJoc();
        
    }//GEN-LAST:event_Buto_pensatActionPerformed

    private void Buto_SIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buto_SIActionPerformed
        // TODO add your handling code here:
        if( esPregunta) {
            preguntaSI();
        }
        else {
            celebracio();
        }
    }//GEN-LAST:event_Buto_SIActionPerformed

    private void Buto_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buto_NOActionPerformed
        // TODO add your handling code here:
        if (esPregunta) {
            preguntaNO();
        }
        else {
            PanellSegon.setVisible(true);
        }
        // falta demanar que entrin animal nou i pregunta
    }//GEN-LAST:event_Buto_NOActionPerformed

    private void Buto_afegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buto_afegirActionPerformed
        // TODO add your handling code here:
        System.out.println("4) Animal entrat ->"+animal.getText()+"<-");
        System.out.println("4) Pregunta entrada ->"+pregunta.getText()+"<-");
        System.out.println("4) Final");
        preguntaNou = pregunta.getText();
        animalNou();
    }//GEN-LAST:event_Buto_afegirActionPerformed

    private void Buto_sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buto_sortirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Buto_sortirActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("static-access")
    public static void main(String args[])  {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Obertura/Creació de la base de dades SQLITE */
        conn.creaBD();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameEndevina().setVisible(true));
    }
    
    private void endevinaAnimal(int id) {
        resultat = conn.llegirAnimal(id);
        // fem printf per veure que em funciona el SELECT
        System.out.printf("nom ->%s<-\n",resultat.get(0));
        System.out.printf("pregunta ->%s<-\n",resultat.get(1));
        System.out.printf("id SI ->%s<-\n", resultat.get(2));
        System.out.printf("id NO ->%s<-\n", resultat.get(3));
        
        if(resultat.get(0).equals("*"))
        {
          //de moment només printf de la pregunta
          System.out.printf("%s ?", resultat.get(1));
          labelPregunta.setText(resultat.get(1)+"?");
          esPregunta = true;
        }
        else {
          labelPregunta.setText("Has pensat '"+resultat.get(0)+"' ?");
          esPregunta = false;
          animalMostrat = resultat.get(0);
          idMostrat = id;
        }
    }
    
    private void preguntaSI() {
        int id;
        //llegir animal apuntador SI
        try {
           id = Integer.parseInt(resultat.get(2));
          }
           catch (NumberFormatException e) {
               id = -1;
           }
        endevinaAnimal(id);

    }

    private void preguntaNO() {
        int id;
        //llegir animal apuntador NO
        try {
           id = Integer.parseInt(resultat.get(3));
          }
           catch (NumberFormatException e) {
               id = -1;
           }
        endevinaAnimal(id);

    }

    private void celebracio() {
        System.out.printf("%s\n", "Celebració!");
        
        Object[] opcions = {"Sí", "No"};

        int n = JOptionPane.showOptionDialog(null,
                "Al·leluia! l'he endevinat. Vols tornar a jugar?",
                "Endevinat",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, //no fem servir icones personalitzades
                opcions, //els títols dels butons
                opcions[0]); // títol del botó per defecte
        System.out.printf("n = %d\n", n);
        // n=0 --> Sí, n=1 --> No
        if(n == 1) { 
            System.exit(0);
        } else
        {
           iniciJoc(); 
        }
    }
    
    private void animalNou() {
        System.out.printf("%s\n","Animal nou. ");

        // compte quants animals hi ha
        var quants = conn.quantsAnimals();
        System.out.printf("Hi ha %d animals\n", quants);

        // inserir l'animal que ha pensat, i pregunta i apuntadors a nul
        conn.inserirAnimal(quants+1, animal.getText());
        System.out.printf("%s\n", "S'ha afegir animal nou");
        
        // inserir l'animal mostrat, i pregunta i apuntadors a nul
        conn.inserirAnimal(quants+2, animalMostrat);
        System.out.printf("%s\n", "S'ha afegir animal anterior");
        
        /*
        modificar l'animal llegit, posant '*' al nom, posant pregunta que ens han donat per distingir, 
        apuntador del Sí apuntant a la fila de l'animal pensat i apuntador del No a la fila de l'animal mostrat
        */
        conn.actualitzarAnimal(idMostrat, preguntaNou, quants+1, quants+2);

        Object[] opcions = {"Sí", "No"};

        int n = JOptionPane.showOptionDialog(null,
                "Vols tornar a jugar?",
                "Animal afegit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, //no fem servir icones personalitzades
                opcions, //els títols dels butons
                opcions[0]); // títol del botó per defecte
        System.out.printf("n = %d\n", n);
        // n=0 --> Sí, n=1 --> No
        if(n == 1) { 
            System.exit(0);
        } else
        {
           iniciJoc(); 
        }
        
    }
    
    private void iniciJoc() {
        PanellSegon.setVisible(false);
        label_pensar.setVisible(false);
        Buto_pensat.setVisible(false);
        System.out.printf("%s\n","Anem a posar visible el PanellPrimer");
        PanellPrimer.setVisible(true);
        System.out.println("PanellPrimer visible ->"+PanellPrimer.isVisible()+"<-");
        // llegir animal #1 --és l'inicial, per començar a preguntar--
        endevinaAnimal(1);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buto_NO;
    private javax.swing.JButton Buto_SI;
    private javax.swing.JButton Buto_afegir;
    private javax.swing.JButton Buto_pensat;
    private javax.swing.JButton Buto_sortir;
    private javax.swing.JPanel PanellPrimer;
    private javax.swing.JPanel PanellSegon;
    private javax.swing.JTextField animal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JLabel label_animal;
    private javax.swing.JLabel label_pensar;
    private javax.swing.JTextField pregunta;
    // End of variables declaration//GEN-END:variables

    private static final connectaBD conn = new connectaBD();
    private ArrayList<String> resultat;
    private boolean esPregunta = true;
    private String animalMostrat = null;
    private String preguntaNou = null;
    private int idMostrat = 0;
}
