<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.tarbaniker</groupId>
    <artifactId>endevina</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <exec.mainClass>com.tarbaniker.endevina.Endevina</exec.mainClass>
    </properties>
    <dependencies>
    <!-- Source: https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
    <dependency>
        <groupId>org.xerial</groupId>
        <artifactId>sqlite-jdbc</artifactId>
        <version>3.53.1.0</version>
        <scope>runtime</scope>
    </dependency>
 
   </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.tarbaniker.endevina.frameEndevina</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                  <execution>
                    <phase>package</phase>
                    <goals>
                      <goal>single</goal>
                    </goals>
                  </execution>
                </executions>
                <configuration>
                    <finalName>endevina-ad-${project.version}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                    <archive>
                        <manifest>
                            <mainClass>com.tarbaniker.endevina.frameEndevina</mainClass>
                        </manifest>
                    </archive>
                  <descriptorRefs>
                    <descriptorRef>jar-with-dependencies</descriptorRef>
                  </descriptorRefs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <phase>test</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo>Using env.test.properties</echo>
                                <copy file="endevina.db" tofile="${basedir}/target/endevina.db"/>
                                </tasks>
                            </configuration>
                        </execution>
                    </executions>
            </plugin>
        </plugins>
    </build>
    <name>Endevina</name>
    <description>Joc d'endevinar l'animal que has pensat. 
L'usuari pensa en un animal i el programa intenta endevinar-lo a través d'una sèrie de preguntes. 
Si no endevina quin animal ha pensat l'usuari, demana quin animal era i quina pregunta ha de fer per distingir-lo dels altres.
Com més s'hi juga més informació té el programa i més probabilitats d'endevinar l'animal.

</description>
</project>